function malat_open(filename)

global malat_fid

if nargin == 0
  filename = 'malat_currdir.sty';
else
  filename = [erase(filename,'.sty'),'.sty'];
end

malat_fid = fopen(filename,'w');

fprintf(malat_fid,[...
  '%%%%%%%% MALAT DATA FILE FROM MATLAB, DO NOT EDIT %%%%%%%%\n',...
  '\\providecommand\\malatprefix{default}\n',...
  '\\providecommand\\M[2][\\malatprefix]{',...
    '\\ifcsname malat-#1-#2\\endcsname\\else',...
      '\\PackageError{MALAT}{Malat variable "#2" with prefix "#1" not defined.}{}',...
    '\\fi',...
    '\\csname malat-#1-#2\\endcsname',...
  '}\n',...
  '\\providecommand\\MSI[3][\\malatprefix]{',...
    '\\ifcsname malat-#1-#2\\endcsname\\else',...
      '\\PackageError{MALAT}{Malat variable "#2" with prefix "#1" not defined.}{}',...
    '\\fi',...
    '\\expandafter\\SI\\expandafter{\\csname malat-#1-#2\\endcsname}{#3}',...
  '}\n',...
  '%%%%%%%% MALAT DATA FILE FROM MATLAB, DO NOT EDIT %%%%%%%%\n',...
  ]);


end